---
title: "Solution GPS"
author: "Marc-André Désautels"
date: "19 mars 2018"
output:
  html_document: 
    toc: yes
    toc_float: yes
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 15)
library(gpsr)
library(linalgr)
library(knitr)
```

```{r data-generation, echo = FALSE, results = "hide", message = FALSE}
data <- readr::read_csv("data/merveilles.csv")
num_merveille <- sample(1:nrow(data), 1)
sat <- creation_gps(data, num_merveille)
```

## Question

Voici les données satellites de l'endroit où vous vous trouvez.

```{r donnees-satellites, echo = FALSE}
kable(sat, align = "c", digits = c(8, 8, 8, 6))
```

## Solution

```{r matrice-solution, echo = FALSE}
# Initialisation des constantes
Rt <- 6378137 # Le rayon moyen de la Terre en metres
Rs <- 20200000 # L'altitude des satellites en metres
c <- 299792458/(Rt*1000) # La vitesse de la lumiere en rayons de la Terre par millisecondes
A <- matrix(0, nrow(sat)-1, 4)
B <- matrix(0, nrow(sat)-1, 1)

for (i in (1:(nrow(sat)-1))){
  A[i, (1:3)] <- 2*(sat[i+1, (2:4)] - sat[1, (2:4)])
  A[i, 4] <- -2*c^2*(sat[i+1, 5] - sat[1, 5])
  B[i] <- sum(sat[(i+1), (2:4)]^2 - sat[1, (2:4)]^2)-c^2*(sat[(i+1), 5]^2 - sat[1, 5]^2)
}

R <- rref(A,B, verbose = FALSE, digits = 15)
K <- R$A[, 4]
L <- R$B
xf <- sat[nrow(sat), (2:4)]
tf <- sat[nrow(sat), 5]

# Coefficient en t^2
a <- sum(K^2)-c^2
# Coefficient en t
b <- sum(-2*(L-xf)*K)+2*c^2*tf
# Coefficient constant
c <- sum((L-xf)^2)-c^2*tf^2

# Resolution de la quadratique
delta <- b^2 - 4*a*c
t1 <- (-b + sqrt(delta))/(2*a)
t2 <- (-b - sqrt(delta))/(2*a)

pos1 <- L - K*t1
pos2 <- L - K*t2
pos <- matrix(c(pos1, pos2), 2, 3, byrow = TRUE)

l1 <- norm(pos[1, ], "2")
l2 <- norm(pos[2, ], "2")

id <- which.min(c(abs(l1-1), abs(l2-1)))

if (id == 1) final <- pos[1,] else final <- pos[2,]

r <- norm(final, "2")
latitude <- rad2deg(asin(final[3]/r))
longitude <- rad2deg(atan2(final[2],final[1]))

```


# Créer plusieurs problèmes

```{r creation-devoir}
N <- 100 # Nombre de problemes differents
num_satellites <- 4
donnees <- lapply(1:N, function(x) matrix(0, num_satellites, 5))
sols <- character(length = N)
for (i in (1:N)){
  numero <- sample(1:nrow(data), 1)
  donnees[[i]] <- creation_gps(data, numero, num_satellites = num_satellites)
  sols[i] <- data[numero, ]$nom
}
```

\newpage

```{r, results='asis', echo=FALSE}
for (i in (1:N)){
  cat(c("###  Exercice ", i, "."))
  print(kable(donnees[[i]], align = "c", digits = c(8, 8, 8, 6)))
  cat("\n")
  if ((i %% 5) == 0) cat("\\newpage\n")
}
```

\newpage

# Solutions

```{r, results = "asis", echo=FALSE}
for (i in (1:N)){
  cat(c("Exercice ", i, ". "))
  cat(sols[i])
  cat("\n\n")
}
```
